version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Initialize node_modules
          command: |
            npm install mocha
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Test
          command: |
            npm run xunit
      - store_test_results:
          path: ~/workspace/results
      - store_artifacts:
          path: ~/workspace/results
          destination: results
